version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment:
          - POSTGRES_DB=pg_service_template_db_1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports:
          - 5432:5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres
    mongo:
        container_name: service-mongo
        image: mongodb/mongodb-community-server
        ports:
          - 27017:27017
        networks:
          - postgres
    pg_service_template-container-replica-1:
        image: cr.yandex/crp37i9qfn16d69aaulp/conference-app:latest
        container_name: backend-service-2
        hostname: backend-2
        privileged: true
        environment:
          - POSTGRES_DB=pg_service_template_db_1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/pg_service_template/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/pg_service_template:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8081:8080
        working_dir: /pg_service_template
        entrypoint:
          - ./docker-entrypoint.sh
        networks:
          - postgres
        depends_on:
          - postgres

    pg_service_template-container-replica-2:
        image: cr.yandex/crp37i9qfn16d69aaulp/conference-app:latest
        container_name: backend-service-3
        hostname: backend-3
        privileged: true
        environment:
          - POSTGRES_DB=pg_service_template_db_1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/pg_service_template/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/pg_service_template:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8082:8080
        working_dir: /pg_service_template
        entrypoint:
          - ./docker-entrypoint.sh
        networks:
          - postgres
        depends_on:
          - postgres

    pg_service_template-container:
        image: cr.yandex/crp37i9qfn16d69aaulp/conference-app:latest
        container_name: backend-service-1
        hostname: backend-1
        privileged: true
        environment:
          - POSTGRES_DB=pg_service_template_db_1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/pg_service_template/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/pg_service_template:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /pg_service_template
        entrypoint:
          - ./tests/run_as_user.sh
        networks:
          - postgres
        depends_on:
          - postgres
          - mongo
          - swagger
          - nginx
          - pg_service_template-container-replica-1
          - pg_service_template-container-replica-2
    swagger:
      image: swaggerapi/swagger-ui
      container_name: swagger
      environment:
        - SWAGGER_JSON=/mnt/swagger/api-spec.yaml
      volumes:
        - ./schemas/openapi/:/mnt/swagger
      ports:
        - 30000:80
      networks:
        - postgres
    nginx:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/static:/usr/share/nginx/html
      networks:
        - postgres
    pg_admin:
      image: dpage/pgadmin4:latest
      container_name: pg_admin
      networks:
        - postgres
      ports:
        - 30001:80
      environment:
        - PGADMIN_DEFAULT_EMAIL=default@email.com
        - PGADMIN_DEFAULT_PASSWORD=password

networks:
    postgres:
        driver: bridge
