EventListGet200Response:
  additionalProperties: false
  type: object
  required:
    - events
  properties:
    events:
      type: array
      items:
        $ref: "/etc/schemas/gen/common.yaml#/Event"
