RequestPostBody:
  type: object
  additionalProperties: false
  required:
    - event_id
    - attachment_ids
  properties:
    event_id:
      description: Related event id
      type: integer
    attachment_ids:
      type: array
      items:
        type: string
        format: uuid
    description:
      description: Description of request
      type: string
RequestPostResponse200:
  additionalProperties: false
  type: object
  required:
    - request_id
  properties:
    request_id:
      type: string
      format: uuid
