version: "2.3"

services:
  postgres:
    image: postgres:12
    hostname: service-postgres
    environment:
      - POSTGRES_DB=pg_service_template_db_1
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./.pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres

  service:
    image: inttest_image
    hostname: backend-1
    privileged: true
    environment:
      - POSTGRES_DB=pg_service_template_db_1
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PREFIX=${PREFIX:-~/.local}
      - CCACHE_DIR=/pg_service_template/.ccache
      - CORES_DIR=/cores
    volumes:
      - ${TC_CORES_DIR:-./.cores}:/cores:rw
      - ./report:/report
    ports:
      - 8080:8080
    entrypoint:
      - /bin/bash
      - /usr/bin/service/tests/run_e2e.sh
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

networks:
  postgres:
    driver: bridge
