worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

dbconnection: 'postgresql://user:password@service-postgres-2:5432/pg_service_template_db_1'
mongoconnection: 'mongodb://service-mongo:27017/admin'

s3region: ru-central1
s3endpoint: storage.yandexcloud.net
usemongo: False
