components_manager:
  task_processors:                  # Task processor is an executor for coroutine tasks

    main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
      worker_threads: $worker-threads         # Process tasks in 4 threads.

    grpc-blocking-task-processor: # For blocking gRPC channel creation
      worker_threads: 2
      thread_name: grpc-worker

    fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
      worker_threads: $worker-fs-threads

  default_task_processor: main-task-processor

  components:
    testsuite-support: {}

    server:
      listener:
        port: $server-port
        task_processor: main-task-processor

    logging:
      fs-task-processor: fs-task-processor
      loggers: {}

    grpc-client-factory:
      middlewares: [ ]
      channel-args: { }

    grpc-client-common:
      # The TaskProcessor for blocking connection initiation
      blocking-task-processor: grpc-blocking-task-processor

    otlp-logger:
      endpoint: '84.201.170.37:4317'
      service-name: conference-app-inttest
      log-level: debug
      # How to rename attributes, if you really need to
      attributes-mapping:
        module: line

    request_int_test: {}

    dynamic-config:
      defaults:
        HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
        POSTGRES_DEFAULT_COMMAND_CONTROL:
          network_timeout_ms: 750
          statement_timeout_ms: 500

    postgres-db-1:
      dbconnection: $dbconnection
      blocking_task_processor: fs-task-processor
      dns_resolver: async
      sync-start: false
      connlimit_mode: manual

    dns-client:
      fs-task-processor: fs-task-processor
