components_manager:
  task_processors:                  # Task processor is an executor for coroutine tasks

    main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
      worker_threads: $worker-threads         # Process tasks in 4 threads.

    fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
      worker_threads: $worker-fs-threads

  default_task_processor: main-task-processor

  components:
    testsuite-support: {}

    server:
      listener:
        port: $server-port
        task_processor: main-task-processor

    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stderr'
          level: $logger-level
          overflow_behavior: discard

    request_int_test: {}

    dynamic-config:
      defaults:
        HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
        POSTGRES_DEFAULT_COMMAND_CONTROL:
          network_timeout_ms: 750
          statement_timeout_ms: 500

    postgres-db-1:
      dbconnection: $dbconnection
      blocking_task_processor: fs-task-processor
      dns_resolver: async
      sync-start: false
      connlimit_mode: manual

    mongo-db:
      dbconnection: $mongoconnection

    dns-client:
      fs-task-processor: fs-task-processor
