#!/bin/bash

CMAKE_CONTENT=$'# THIS FILE IS AUTOGENERATED. DON\'T EDIT\n\n'
CMAKE_CONTENT+=$'add_library(${PROJECT_NAME}_gen OBJECT\n'

FILES="$(find -E src/gen -regex ".*(hpp|cpp|ipp)" -type f)"
CMAKE_CONTENT+="$FILES"

CMAKE_CONTENT+=$')\n'
CMAKE_CONTENT+=$'target_link_libraries(${PROJECT_NAME}_gen PUBLIC userver::postgresql)'

echo "$CMAKE_CONTENT" > src/gen/CMakeLists.txt
