name: CI. Should run after every push to this repo

on: [push, pull_request]

jobs:
  Build-docker-image:
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.set-docker-tag.outputs.docker-tag }}
    steps:
      - name: Set up dependencies
        run: docker --version

      - name: Pull Docker image
        run: |
          docker pull cr.yandex/crp37i9qfn16d69aaulp/conference-app:latest

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run codegen
        run: make gen

      - name: Build service and tests
        run: |
          docker run -t -v .:/code cr.yandex/crp37i9qfn16d69aaulp/conference-app:latest /bin/bash /code/ci/run_build.sh

      - name: Build docker image
        run: |
          export DOCKER_TAG=cr.yandex/crp37i9qfn16d69aaulp/conference_app:github_run_${GITHUB_RUN_ID}
          docker build . --network=host -f docker/release/Dockerfile --tag ${DOCKER_TAG}

      - name: Upload docker image
        run: |
          export DOCKER_TAG=cr.yandex/crp37i9qfn16d69aaulp/conference_app:github_run_${GITHUB_RUN_ID}
          docker push ${DOCKER_TAG}

      - name: Set docker tag
        id: set-docker-tag
        run: |
          export DOCKER_TAG=cr.yandex/crp37i9qfn16d69aaulp/conference_app:github_run_${GITHUB_RUN_ID}
          echo "docker-tag=$DOCKER_TAG" >> $GITHUB_OUTPUT

#      - name: Set docker tag
#        id: set-docker-tag
#        run: |
#          export DOCKER_TAG=cr.yandex/crp37i9qfn16d69aaulp/conference_app:github_run_12048627744
#          echo "docker-tag=$DOCKER_TAG" >> $GITHUB_OUTPUT

  Run-tests:
    runs-on: ubuntu-latest
    needs: Build-docker-image
    steps:
      - name: Pull service image
        run: |
          docker pull "${{ needs.Build-docker-image.outputs.docker-tag }}"

      - name: Rename image
        run: |
          docker tag ${{ needs.Build-docker-image.outputs.docker-tag }} inttest_image

      - name: Run unittests
        run: >
          docker run -t inttest_image /usr/bin/service/pg_service_template_unittest --gtest_output=xml:/report.xml

      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: unittest_report
          path: report.xml
          retention-days: 3

      - name: Pull postgres image
        run: docker pull postgres:12

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run integration tests
        run: docker compose -f docker/inttest/docker-compose.yaml run service || true

      - name: Stop all containers
        run: docker stop $(docker ps -a -q)

      - name: Run e2e tests
        run: docker compose -f docker/e2e/docker-compose.yaml run service --build

      - name: Stop all containers
        run: docker stop $(docker ps -a -q)
