name: CI. Should run after every push to this repo

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up dependencies
        run: docker --version
      - name: Pull docker images
        run: |
          docker pull cr.yandex/crp37i9qfn16d69aaulp/conference-app:latest
      - name: Clone repository
        uses: actions/checkout@v4
      - name: 123
        run: ls -al
      - name: Build service
        run: | 
          docker run -t -v db_course_work:/code cr.yandex/crp37i9qfn16d69aaulp/conference-app:latest /bin/bash /code/run_build.sh
