name: CI. Should run after every push to this repo

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up dependencies
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Pull docker images
        run: |
          docker pull postgres:12
#          docker pull mongodb/mongodb-community-server
#          docker pull cr.yandex/crp37i9qfn16d69aaulp/conference-app:latest
#          docker pull swaggerapi/swagger-ui
#          docker pull dpage/pgadmin4:latest
#          docker pull nginx
      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Build service
        run: make docker-cmake-debug
      - name: Run unittests
        run: make docker-unittest
