name: CI. Should run after every push to this repo

on: [push, pull_request]

jobs:
  Build-docker-image:
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.set-output.outputs.docker-tag }}
    steps:
      - name: Set up dependencies
        run: docker --version

      - name: Pull Docker image
        run: |
          docker pull cr.yandex/crp37i9qfn16d69aaulp/conference-app:latest

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run codegen
        run: make gen

      - name: Build service and tests
        run: | 
          docker run -t -v .:/code cr.yandex/crp37i9qfn16d69aaulp/conference-app:latest /bin/bash /code/ci/run_build.sh

      - name: Build docker image
        run: |
          export DOCKER_TAG=cr.yandex/crp37i9qfn16d69aaulp/conference_app:github_run_${GITHUB_RUN_ID}
          docker build . --network=host -f docker/release/Dockerfile --tag ${DOCKER_TAG}

      - name: Upload docker image
        run: |
          export DOCKER_TAG=cr.yandex/crp37i9qfn16d69aaulp/conference_app:github_run_${GITHUB_RUN_ID}
          docker push ${DOCKER_TAG}

      - name: Set docker tag
        run: |
          export DOCKER_TAG=cr.yandex/crp37i9qfn16d69aaulp/conference_app:github_run_${GITHUB_RUN_ID}
          echo $DOCKER_TAG >> $GITHUB_OUTPUT


  Run-tests:
    runs-on: ubuntu-latest
    needs: Build-docker-image
    steps:
      - name: Print version
        run: |
          echo "${{ needs.Build-docker-image.outputs.docker-tag }}"
